/**
 * Tool argument validation.
 *
 * MCP tool schemas are full JSON Schema 2020-12, so a draft-07 validator would
 * silently ignore composition keywords and pass arguments the server will
 * reject — or worse, accept ones it should not.
 *
 * Schemas come from third-party servers, so the validator is configured
 * defensively: no remote refs, no code generation surprises, and a compile
 * failure is treated as a validation failure rather than an exception that
 * takes down a run.
 */
import { Ajv2020 } from 'ajv/dist/2020';
import addFormats from 'ajv-formats';
import type { ValidateFunction } from 'ajv';

export interface ValidationResult {
  readonly valid: boolean;
  readonly errors: readonly string[];
}

const VALID: ValidationResult = Object.freeze({ valid: true, errors: [] });

export class SchemaValidator {
  readonly #ajv: Ajv2020;
  readonly #compiled = new Map<string, ValidateFunction | null>();

  constructor() {
    this.#ajv = new Ajv2020({
      // Report every problem: a model correcting one error at a time burns a
      // round trip per field.
      allErrors: true,
      // Arguments are generated by a model and frequently carry an extra key;
      // stripping is friendlier than refusing, and the server sees only what
      // its own schema declared.
      removeAdditional: 'failing',
      useDefaults: true,
      coerceTypes: false,
      // A third-party schema must not make us fetch anything.
      loadSchema: undefined as never,
      strict: false,
      validateFormats: true,
    });
    addFormats(this.#ajv as never);
  }

  /**
   * Compiles once per schema hash.
   *
   * A schema that cannot compile is cached as null so a broken server costs one
   * compile attempt rather than one per call.
   */
  #compile(schemaKey: string, schema: unknown): ValidateFunction | null {
    const cached = this.#compiled.get(schemaKey);
    if (cached !== undefined) return cached;

    let compiled: ValidateFunction | null;
    try {
      compiled = this.#ajv.compile(schema as object);
    } catch {
      compiled = null;
    }
    this.#compiled.set(schemaKey, compiled);
    return compiled;
  }

  validate(schemaKey: string, schema: unknown, args: unknown): ValidationResult {
    // A tool with no schema declares no constraints. Refusing would break every
    // zero-argument tool.
    if (schema === undefined || schema === null) return VALID;

    const validator = this.#compile(schemaKey, schema);
    if (validator === null) {
      return {
        valid: false,
        errors: [
          'The tool\'s input schema could not be compiled, so arguments cannot be checked. ' +
          'This is a fault in the server\'s tool definition.',
        ],
      };
    }

    // Ajv mutates the argument object for removeAdditional/useDefaults, which
    // is intended: the server receives exactly what its schema declared.
    const ok = validator(args);
    if (ok) return VALID;

    return {
      valid: false,
      errors: (validator.errors ?? []).map((error) => {
        const path = error.instancePath === '' ? '(root)' : error.instancePath;
        return `${path} ${error.message ?? 'is invalid'}`;
      }),
    };
  }
}
